server:
  port: 8089
  servlet:
    context-path: /business
#  address: 127.0.0.1
spring:
  application:
    name: business
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://120.48.75.107:3306/aragon
    url: jdbc:mysql://127.0.0.1:3306/aragon
    username: root
    password: aragon@ky123
  redis:
    host: 127.0.0.1
    #host: 120.48.75.107
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: aragon@ky123
    #连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0
      #连接超时时间（毫秒）
    timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: 120.48.75.107:8848
        namespace: 983c226c-68ec-4c43-bbd5-ddc627085f9d
      config:
        server-addr: 127.0.0.1:8848
        #server-addr: 120.48.75.107:8848
        group: DEFAULT_GROUP
        file-extension: properties
        namespace: 983c226c-68ec-4c43-bbd5-ddc627085f9d
  config:
    import: nacos:${spring.application.name}-${spring.profiles.active}.properties

logging:
  level:
    # 默认所有都是info级别
    root: info
    com.cloud: debug
