server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: nacos:gateway-${spring.profiles.active}.properties
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: 120.48.75.107:8848
        namespace: 983c226c-68ec-4c43-bbd5-ddc627085f9d
      config:
        server-addr: 127.0.0.1:8848
        #server-addr: 120.48.75.107:8848
        group: DEFAULT_GROUP
        file-extension: properties
        namespace: 983c226c-68ec-4c43-bbd5-ddc627085f9d
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      # 路由数组：指当请求满足什么样的断言时，转发到哪个服务上
      routes:
        # 路由标识，要求唯一，名称任意
        - id: gateway-provider_common
          # 请求最终被转发到的目标地址
#          uri: http://localhost:8088
          uri: lb://common/
          # 设置断言
          predicates:
            - Path=/common/**
            - Weight=group1, 8
          # 配置过滤器（局部）
#          filters:
#            - StripPrefix=1

        - id: gateway-provider_business
          uri: lb://business/
          predicates:
            - Path=/business/**
            - Weight=group2, 8

logging:
  level:
    org.springframework.cloud.gateway: debug
